name: CI
on: [pull_request]
jobs:
  test-skip-install-and-use-bundler:
    name: runner / rubocop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/using_bundler
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/using_bundler/Gemfile
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all commits for PR branch plus head commit of base branch
        run: |
          # fetch all commits of the PR branch
          git fetch --shallow-exclude "${{ github.base_ref }}" origin "${{ github.ref }}"
          # fix for "fatal: error in object: unshallow"
          git repack -d
          # fetch head commit of base branch
          git fetch --deepen 1 origin "${{ github.ref }}"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: rubocop with skip install and using bundler
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          skip_install: 'true'
          use_bundler: 'true'
      - run: test "$(bundle exec rubocop --version)" == "1.18.1"
